name: PR Validation

on:
  pull_request:
    types: [ opened, synchronize, reopened ]
    branches: [ main ]

permissions:
  contents: read
  pull-requests: write

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      # Quick lint and format check
      - name: Lint
        run: npm run lint

      # Optional: Add PR status checks
      - name: PR Title Checker
        uses: actions/github-script@v7
        with:
          script: |
            const title = context.payload.pull_request.title;
            const pattern = /^(feat|fix|docs|style|refactor|perf|test|chore)(\(.+\))?: .+/;

            if (!pattern.test(title)) {
              core.setFailed('PR title does not follow conventional commit format');
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.payload.pull_request.number,
                body: '⚠️ PR title should follow the [Conventional Commits](https://www.conventionalcommits.org/) format.'
              });
            }
